// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AccountEntry account entry
//
// swagger:model AccountEntry
type AccountEntry struct {

	// email
	Email string `json:"email,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// user id
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this account entry
func (m *AccountEntry) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this account entry based on context it is used
func (m *AccountEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AccountEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountEntry) UnmarshalBinary(b []byte) error {
	var res AccountEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
