// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Company Rest API
//
//	Company REST API for Baremetal Scenarios
//	Schemes:
//	  http
//	Host: 0.0.0.0:11111
//	BasePath: /company_name/v1
//	Version: 0.0.1
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
