name: TEST
on:
  schedule:
    - cron: "5 * * * THU,SAT"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "It's time to mentoring"